### ISSUE TITLE
Dokumentera

### ISSUE THREAD

**Issue by thecyclingfarmer** [KnowitReaktorUX/reaktorbase#5]

**Comment by fkarlin** [comment]
Dokumentera bl.a. hur man konfigurerar gulp-accessibility mot A, AA eller AAA.

**Comment by fkarlin** [comment]
Behövs läggas in Access sniff för att kunna konfigurera – https://github.com/yargalot/AccessSniff

**Comment by fkarlin** [comment]
Fixat med gulp-wcag-accessibility!
